name: My First Workflowf
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest

    steps:
      - run: echo "👋 Hello World!"

      - name: Checkout
        uses: actions/checkout@4.1.4

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
